CC=cc
CFLAGS=-Wall

all: pipetest AlrmTest directory_traverse_breadth_first smallsh

pipetest:
	@echo $@ not yet written

AlrmTest:
	@echo $@ not yet written

directory_traverse_breadth_first:
	@echo $@ not yet written

smallsh: smallsh.c smallsh.h
	$(CC) $(CFLAGS) $< -o $@


.PHONY: clean
clean:
	rm -f *.o core
